// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TransporationLineType_AddModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TransporationLineType_AddModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201906040755476_TransporationLineType_AddModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
